### ISSUE TITLE
HUD is outside of sweetspot

### ISSUE THREAD

**Issue by chrisunfocused** [DrBibop/RoR2VRMod#14]
HP Reverb G2. UI is never in focus. Maybe add an option to scale the head tracking impact on the UI movement so that the corners of the HUD can be viewed

**Comment by DrBibop** [comment]
The HUD is indeed not perfect right now. I'll try to find a solution for this but the main problem is the crosshair being part of that HUD. I'll see what I can do.

**Comment by chrisunfocused** [comment]
Ahhhh. True. I'm not really sure what a good solution would be. I'll ponder it in the shower.

**Comment by DrBibop** [comment]
Good news! The crosshair has been separated from the rest of the HUD since the anniversary update. I also noticed that I already fixed the top part of the HUD but the update broke it.

**Comment by chrisunfocused** [comment]
The HUD still appears to be bound to the crosshair position. Are there plans to change this behaviour?

**Comment by DrBibop** [comment]
It is indeed bound to it. I lowered the top part so its more visible but is it still too hard to see? I wish I could test with more headsets but I thought it would look fine since the G2 has pretty much the same FOV as my Rift S. Can you elaborate on whats still hard to see?

**Comment by chrisunfocused** [comment]
I getcha. I was under the impression that it was unbound following the anniversary update.The issue I have is that the hud is always in my peripheral vision, which makes it difficult to read. Hard to get a good understanding of your pickups, cooldowns etc.My ideal outcome would be if it could be untethered from the cross hair, so that I can view the hud in the center of my vision, but I understand if that's not possible.On 5/04/2021 8:01 pm, DrBibop ***@***.***> wrote:
It is indeed bound to it. I lowered the top part so its more visible but is it still too hard to see? I wish I could test with more headsets but I thought it would look fine since the G2 has pretty much the same FOV as my Rift S. Can you elaborate on whats still hard to see?

**Comment by DrBibop** [comment]
Its possible for sure but I'm not too convinced this is the best way to fix the problem. If an enemy is hidden behind the HUD while youre trying to aim with your head, it's just in the way. I guess I can simply make it optional for those that prefer it that way. Thanks for your input.

**Comment by DrBibop** [comment]
Ok so turns out it would be a lot harder than I thought to make the HUD static with the crosshair following the camera. I'm not too much of a fan of this solution anyway. As an alternative, would you like an option to change the width and height of the HUD?

**Comment by DrBibop** [comment]
Added HUD settings. Gonna close this issue if everything is ok on your side.
